# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(696, 382)
        self.gridLayout = QtGui.QGridLayout(Dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.groupBox_4 = QtGui.QGroupBox(Dialog)
        self.groupBox_4.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_initialImage = QtGui.QLabel(self.groupBox_4)
        self.label_initialImage.setObjectName(_fromUtf8("label_initialImage"))
        self.gridLayout_4.addWidget(self.label_initialImage, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setMinimumSize(QtCore.QSize(200, 200))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_finalImage = QtGui.QLabel(self.groupBox_3)
        self.label_finalImage.setObjectName(_fromUtf8("label_finalImage"))
        self.gridLayout_5.addWidget(self.label_finalImage, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.groupBox_3)
        self.gridLayout.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.horizontalSlider_lowRed = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_lowRed.setMaximum(255)
        self.horizontalSlider_lowRed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lowRed.setObjectName(_fromUtf8("horizontalSlider_lowRed"))
        self.horizontalLayout.addWidget(self.horizontalSlider_lowRed)
        self.spinBox_lowRed = QtGui.QSpinBox(self.groupBox)
        self.spinBox_lowRed.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_lowRed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_lowRed.setMaximum(255)
        self.spinBox_lowRed.setObjectName(_fromUtf8("spinBox_lowRed"))
        self.horizontalLayout.addWidget(self.spinBox_lowRed)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalSlider_lowGreen = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_lowGreen.setMaximum(255)
        self.horizontalSlider_lowGreen.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lowGreen.setObjectName(_fromUtf8("horizontalSlider_lowGreen"))
        self.horizontalLayout_2.addWidget(self.horizontalSlider_lowGreen)
        self.spinBox_lowGreen = QtGui.QSpinBox(self.groupBox)
        self.spinBox_lowGreen.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_lowGreen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_lowGreen.setObjectName(_fromUtf8("spinBox_lowGreen"))
        self.horizontalLayout_2.addWidget(self.spinBox_lowGreen)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(50, 0))
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalSlider_lowBlue = QtGui.QSlider(self.groupBox)
        self.horizontalSlider_lowBlue.setMaximum(255)
        self.horizontalSlider_lowBlue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_lowBlue.setObjectName(_fromUtf8("horizontalSlider_lowBlue"))
        self.horizontalLayout_3.addWidget(self.horizontalSlider_lowBlue)
        self.spinBox_lowBlue = QtGui.QSpinBox(self.groupBox)
        self.spinBox_lowBlue.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_lowBlue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_lowBlue.setObjectName(_fromUtf8("spinBox_lowBlue"))
        self.horizontalLayout_3.addWidget(self.spinBox_lowBlue)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(50, 0))
        self.label_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_4.addWidget(self.label_4)
        self.horizontalSlider_highRed = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_highRed.setMaximum(255)
        self.horizontalSlider_highRed.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_highRed.setObjectName(_fromUtf8("horizontalSlider_highRed"))
        self.horizontalLayout_4.addWidget(self.horizontalSlider_highRed)
        self.spinBox_highRed = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_highRed.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_highRed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_highRed.setMaximum(255)
        self.spinBox_highRed.setObjectName(_fromUtf8("spinBox_highRed"))
        self.horizontalLayout_4.addWidget(self.spinBox_highRed)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(50, 0))
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_5.addWidget(self.label_5)
        self.horizontalSlider_highGreen = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_highGreen.setMaximum(255)
        self.horizontalSlider_highGreen.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_highGreen.setObjectName(_fromUtf8("horizontalSlider_highGreen"))
        self.horizontalLayout_5.addWidget(self.horizontalSlider_highGreen)
        self.spinBox_highGreen = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_highGreen.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_highGreen.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_highGreen.setMaximum(255)
        self.spinBox_highGreen.setObjectName(_fromUtf8("spinBox_highGreen"))
        self.horizontalLayout_5.addWidget(self.spinBox_highGreen)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(50, 0))
        self.label_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_6.addWidget(self.label_6)
        self.horizontalSlider_highBlue = QtGui.QSlider(self.groupBox_2)
        self.horizontalSlider_highBlue.setMaximum(255)
        self.horizontalSlider_highBlue.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_highBlue.setObjectName(_fromUtf8("horizontalSlider_highBlue"))
        self.horizontalLayout_6.addWidget(self.horizontalSlider_highBlue)
        self.spinBox_highBlue = QtGui.QSpinBox(self.groupBox_2)
        self.spinBox_highBlue.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBox_highBlue.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_highBlue.setMaximum(255)
        self.spinBox_highBlue.setObjectName(_fromUtf8("spinBox_highBlue"))
        self.horizontalLayout_6.addWidget(self.spinBox_highBlue)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_8.addWidget(self.groupBox_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_loadImage = QtGui.QPushButton(Dialog)
        self.pushButton_loadImage.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_loadImage.setObjectName(_fromUtf8("pushButton_loadImage"))
        self.verticalLayout_3.addWidget(self.pushButton_loadImage)
        self.pushButton_close = QtGui.QPushButton(Dialog)
        self.pushButton_close.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_close.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 4);"))
        self.pushButton_close.setObjectName(_fromUtf8("pushButton_close"))
        self.verticalLayout_3.addWidget(self.pushButton_close)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout_8, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Initial Image", None))
        self.label_initialImage.setText(_translate("Dialog", "TextLabel", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Final Image", None))
        self.label_finalImage.setText(_translate("Dialog", "TextLabel", None))
        self.groupBox.setTitle(_translate("Dialog", "Lower threshold", None))
        self.label.setText(_translate("Dialog", "Red", None))
        self.label_2.setText(_translate("Dialog", "Green", None))
        self.label_3.setText(_translate("Dialog", "Blue", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Higher threshold", None))
        self.label_4.setText(_translate("Dialog", "Red", None))
        self.label_5.setText(_translate("Dialog", "Green", None))
        self.label_6.setText(_translate("Dialog", "Blue", None))
        self.pushButton_loadImage.setText(_translate("Dialog", "Load Image", None))
        self.pushButton_close.setText(_translate("Dialog", "Close", None))

